import { StyleSheet } from 'react-native';
import { colors } from './colors';
import { typography } from './typography';
import { spacing } from './spacing';
import { shadows } from './shadows';

export const mapScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  safeAreaContent: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerContainer: {
    flexDirection: 'row',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.screenPaddingHorizontal,
    paddingTop: 12,
    paddingBottom: spacing.paddingMedium,
    backgroundColor: colors.card,
    borderBottomWidth: 2,
    borderBottomColor: colors.divider,
    ...shadows.header,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F8F9FA',
    alignItems: "center",
    justifyContent: "center",
    ...shadows.button,
  },
  backButtonText: {
    fontSize: 18,
    color: colors.textPrimary,
    fontWeight: "600",
  },
  headerRight: {
    width: 40,
  },
  headerImage: {
    height: 24,
  },
  headerTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  headerIcon: {
    fontSize: 32,
    marginRight: 12,
  },
  headerTextContainer: {
    flexDirection: "column",
    alignItems: "center",
  },
  headerTitle: {
    ...typography.h2,
    color: colors.textPrimary,
    fontWeight: "700",
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 2,
    fontWeight: "400",
  },
  headerActionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F8F9FA',
    alignItems: "center",
    justifyContent: "center",
    ...shadows.button,
  },
  headerActionIcon: {
    fontSize: 20,
    color: colors.textPrimary,
  },
  searchContainer: {
    marginHorizontal: 18,
    marginTop: 16,
    marginBottom: 4,
    paddingHorizontal: spacing.paddingMedium,
    paddingVertical: 2,
    backgroundColor: colors.surface,
    borderRadius: spacing.borderRadiusLarge,
    borderColor: "#00000030",
    borderWidth: 1,
    borderBottomWidth: 1,
    borderBottomColor: "#00000030",
    ...shadows.card,
    shadowColor: "#000",
    shadowOffset: {
      width: 4,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 6,
    paddingHorizontal: 4,
  },
  searchInput: {
    ...typography.body1,
    flex: 1,
    color: colors.textPrimary,
    paddingLeft: 0,
  },
  searchClearButton: {
    padding: 5,
  },
  searchClearText: {
    fontSize: 18,
    color: colors.textSecondary,
  },
  searchResultsContainer: {
    marginTop: spacing.paddingSmall,
    paddingHorizontal: spacing.paddingSmall,
  },
  searchResultsList: {
    marginTop: spacing.paddingSmall,
  },
  searchResultsTitle: {
    ...typography.body1,
    color: colors.textPrimary,
    marginBottom: spacing.paddingSmall,
    fontWeight: "600",
  },
  searchSuggestionsContainer: {
    marginBottom: spacing.paddingSmall,
  },
  searchSuggestionsTitle: {
    ...typography.body1,
    color: colors.textSecondary,
    marginBottom: spacing.paddingSmall,
    fontWeight: "600",
  },
  searchLoading: {
    paddingVertical: spacing.paddingSmall,
    alignItems: 'center',
  },
  searchLoadingText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  noSearchResults: {
    paddingVertical: spacing.paddingSmall,
    alignItems: 'center',
  },
  noSearchResultsText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  categoryRow: {
    flexDirection: "row",
    marginBottom: 10,
    marginHorizontal: 35,
  },
  categoryContainer: {
    marginTop: 4,
    marginBottom: 4,
    marginHorizontal: spacing.screenPaddingHorizontal,
    alignItems: 'center',
  },
  categoryTitle: {
    fontSize: 16,
    color: colors.textPrimary,
    marginTop: 4,
    fontWeight: '500',
  },
  categoryScrollContainer: {
    marginTop: 8,
    paddingRight: spacing.paddingMedium,
  },
  categoryCard: {
    borderColor:  "#00000030",
    borderRadius: 6,
    borderWidth: 1,
    paddingVertical: 4,
    marginRight: 8,
    marginBottom: 6,
    backgroundColor: "#fff",
    width: 90,
    height: 120,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectedCategoryCard: {
    borderColor: "#64a66788",
    backgroundColor: "#E8F5E8",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 1,
    elevation: 4,
  },
  categoryCardDisabled: {
    opacity: 0.9,
  },
  categoryIconWrap: {
    marginTop: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryIconBg: {
    height: 55,
    width: 55,
    backgroundColor: "#0000000D",
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
  },
  selectedCategoryIconBg: {
    backgroundColor: "#4CAF50",
  },
  categoryIcon: {
    fontSize: 30,
    textAlign: "center",
    textAlignVertical: "center",
    lineHeight: 50,
  },
  categoryLabel: {
    color: "#000000b0",
    fontSize: 13,
    textAlign: "center",
    fontWeight: "100",
    marginBottom: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 50,
  },
  loadingText: {
    ...typography.body1,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 16,
    fontWeight: '600',
  },
  loadingSubText: {
    ...typography.body2,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
    opacity: 0.8,
  },
  mapLoadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  mapLoadingContainer: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    ...shadows.card,
  },
  mapLoadingText: {
    ...typography.body1,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 12,
    fontWeight: '600',
  },
  mapLoadingSubText: {
    ...typography.body2,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 6,
    fontStyle: 'italic',
    opacity: 0.8,
  },
  reviewLoadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  reviewLoadingText: {
    ...typography.body2,
    color: colors.textSecondary,
    marginLeft: 8,
  },
  mapImageBg: {
    borderRadius: 6,
  },
  mapImageBgWrap: {
    alignItems: "center",
    paddingVertical: 137,
    paddingHorizontal: 16,
    marginBottom: 25,
    marginHorizontal: 38,
  },
  mapIcon: {
    borderRadius: 6,
    width: 24,
    height: 24,
    marginBottom: 8,
  },
  mapText: {
    color: "#000000",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  noMarginRight: {
    marginRight: 0,
  },
  reportButton: {
    backgroundColor: "#4CAF50",
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 24,
    marginHorizontal: 2,
    alignItems: "center",
    shadowColor: "#0000001c",
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 4,
  },
  reportButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "500",
  },
  searchResultItem: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  searchResultContent: {
    flexDirection: "column",
  },
  searchResultName: {
    ...typography.body1,
    fontWeight: "bold",
    color: colors.textPrimary,
  },
  searchResultAddress: {
    ...typography.body2,
    color: colors.textSecondary,
    marginTop: 2,
  },
  searchSuggestionItem: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  searchSuggestionText: {
    ...typography.body2,
    color: colors.textSecondary,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    width: '90%',
    maxHeight: '80%',
    ...shadows.card,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  modalTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  modalTitle: {
    ...typography.h4,
    color: colors.textPrimary,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  favoriteButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: colors.surface,
  },
  favoriteButtonText: {
    fontSize: 20,
    opacity: 0.7,
  },
  favoriteButtonTextActive: {
    opacity: 1,
  },
  closeButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: colors.surface,
  },
  closeButtonText: {
    fontSize: 20,
    color: colors.textSecondary,
    fontWeight: 'bold',
  },
  modalBody: {
    padding: 20,
  },
  categoryBadge: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  categoryBadgeText: {
    ...typography.body2,
    color: colors.background,
    fontWeight: '600',
  },
  infoSection: {
    marginBottom: 16,
  },
  infoLabel: {
    ...typography.body2,
    color: colors.textSecondary,
    marginBottom: 6,
    fontWeight: '600',
  },
  infoValue: {
    ...typography.body1,
    color: colors.textPrimary,
    lineHeight: 20,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.primary,
  },
  modalButtonText: {
    ...typography.button,
    color: colors.primary,
  },
  primaryButton: {
    backgroundColor: colors.primary,
  },
  primaryButtonText: {
    color: colors.background,
  },
  viewToggleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginHorizontal: 16,
    marginTop: 2,
    marginBottom: 4,
    backgroundColor: colors.surface,
    borderRadius: 8,
    borderColor: "#0000001e",
    borderWidth: 1,
    padding: 4,
  },
  viewToggleButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 6,
    marginHorizontal: 2,
  },
  viewToggleButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  viewToggleText: {
    fontSize: 15,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  viewToggleTextActive: {
    color: colors.background,
    fontWeight: '500',
  },
  clearButton: {
    padding: 5,
  },
  clearButtonText: {
    fontSize: 18,
    color: colors.textSecondary,
  },
  placeListItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    ...shadows.card,
  },
  placeListItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  placeListItemIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F0F0F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  placeListItemIconText: {
    fontSize: 24,
    color: '#666',
  },
  placeListItemContent: {
    flex: 1,
    marginRight: 10,
  },
  placeListItemName: {
    fontSize: 18,
    fontWeight: "500",
    color: colors.textPrimary,
  },
  placeListItemCategory: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  placeListItemMeta: {
    alignItems: 'flex-end',
  },
  placeListItemDistance: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: '500',
    marginBottom: 4,
  },
  placeListItemAddress: {
    fontSize: 16,
    color: colors.textPrimary,
    marginBottom: 8,
    marginTop: 8,
    marginLeft: 4,
  },
  placeListItemDescription: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 8,
    marginLeft: 4,
  },
  placeListItemFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  placeListItemDetail: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: '500',
  },
  mainMap: {
    flex: 1,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 16,
    borderRadius: 6,
    borderColor: "#7c7c7c2b",
    borderWidth: 1,
    overflow: 'hidden',
    minHeight: 300, // TODO: 현재는 최소 크기 정해놓음 -> 비율로 수정
  },
  listContainer: {
    flex: 1,
  },
  listContentContainer: {
    paddingBottom: spacing.paddingMedium,
  },
  listHeader: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  listHeaderTitle: {
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: '500',
  },
  listHeaderSubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 4,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 50,
  },
  emptyText: {
    ...typography.body1,
    color: colors.textSecondary,
  },
  actionButtons: {
    marginHorizontal: 16,
    marginBottom: 20,
  },
});
